(define (quadratic-roots a b c)
  (let ((x 4) (y (* a c)) (z (expt b 2))) 
   (let ((d (sqrt (- z (* x y)))))
     (if (> d 0)
      (let ((x1 (+ d b)) (x2 (- d b)))
        (let ((r1 (/ x1 (* 2 a)))(r2 (/ (/ x2 (* 2 a)))))
        (list r1 r2)
        )
       )
      )
     (if (= d 0)
      (let ((x3 (+ d b)))
        (let ((r3 (/ x3 (* 2 a))))
          (list r3)
          )
        )
      )
     (if (< d 0)
         (let ((x4 (+ d b)) (x5 (- d b)))
           (let ((r4 (/ x4 (* 2 a))) (r5 (/ x5 (* 2 a))))
             (list r4 r5)
             )
           )
         )
    )
  )
)
(quadratic-roots 3 7 2)
(quadratic-roots 5 6 1)
(quadratic-roots 5 2 1)
;(quadratic-roots 1 -4 25/4)
(quadratic-roots 0 2 1)


